### ISSUE TITLE
API: a new name for the digital twin platfrom API

### ISSUE THREAD

**Issue by LIN810116** [ABI-CTT-Group/digitaltwins-api#30]
We need a new name for the API to replace the current name DTP

repo name: unchanged?

Let's brainstorm and leave your comments below

**Comment by LIN810116** [comment]
currently it is DTP - but we cannot use this one

**Comment by PrasadBabarendaGamage** [comment]
12 Labours DigitalTWINS (Digital Translational Workflows for Integrating Systems) Platform

**Comment by LIN810116** [comment]
Yes the entire project can be 12 Labours DigitalTWINS Platform which includes:
- [12-labours-app](https://github.com/ABI-Software/12-labours-app)
- [12-labours-api](https://github.com/ABI-Software/12-labours-api)
- Gen3
- iRODS
- [sparc-me](https://github.com/SPARC-FAIR-Codeathon/sparc-me)
- [sparc-flow](https://github.com/SPARC-FAIR-Codeathon/sparc-flow)
- **and the current digital twin platform repo: https://github.com/ABI-CTT-Group/digital-twin-platform**
    - There is no official naming convention for GitHub repositories, but most of the repositories use lowercase and hyphens. so shall we rename the repository digital-twin-platform to `12-labours-digital-twins-api` for only the API interacting with the platform? do we need 12-labours in the name?
    - we can later create another repository (e.g. 12-labours-digital-twins-platform) if we need to warp the entire platform into e.g. a docker compose.
    - According to the Python package naming conventions based on [PEP style](https://peps.python.org/pep-0008/#package-and-module-names),  `Python packages should also have short, all-lowercase names, although the use of underscores is discouraged.` We could name the package `12_labours_digital_twins` or just `digital_twins `. then we it can be installed or used by:
        - `pip install digital_twins `
        - `import digital_twins`  or `from digital_twins import Uploader`

**Comment by LIN810116** [comment]
API name: `twelve-labours-dts`

**Comment by LIN810116** [comment]
api: digitaltwins
repo: digitaltwins-api
