### ISSUE TITLE
Tutorial 5: Uploading datasets to the DigitalTWINS platform using the digitaltwins-api

### ISSUE THREAD

**Issue by LIN810116** [ABI-CTT-Group/digitaltwins-api#35]
This tutorial shows how to upload SDS datasets to the 12 LABOURS DigitalTWINS Platform using its Python API.

**Comment by PrasadBabarendaGamage** [comment]
Text for tutorial is located at the bottom of the Digital Twin Platform User Documentation google doc https://docs.google.com/document/d/10dQ0Cyq0NQ1JlxPYCVtGCIY2umZrYzhAltsyRd9QhgY/edit

**Comment by LIN810116** [comment]
This tutorial has been changed from "Query existing datasets" to "Uploading datasets to the DigitalTWINS platform using the digitaltwins-api"
